# DataFrame

#### DataFrames can be created in 3 ways :
#### 1. Lists --> datafrane
#### 2. Dictionary--> dataframe
#### 3. read_csv--> dataframe

In [12]:
# datafarme ---> combination of Rows and Columns --> 2D Data Structure
rows = [[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]]

In [13]:
import pandas as pd

In [14]:
list_data= pd.DataFrame(rows,columns=['a','b','c'])

In [15]:
print(list_data)

    a   b   c
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
4  13  14  15

In [16]:
list_data.shape

(5, 3)

In [17]:
# Dictionary --> dataframe
# Dictionary --> dataframe ---> rows & column combination
dict_data = {'Name':['Tom', 'nick', 'krish', 'jack'], 'Age':[20, 21, 19, 18]}

In [18]:
Dict_data=pd.DataFrame(dict_data)

In [19]:
print(Dict_data)

    Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18

In [20]:
df= pd.read_csv('dating_app_behavior_dataset.csv')

In [21]:
df

,gender,sexual_orientation,location_type,income_bracket,education_level,interest_tags,app_usage_time_min,app_usage_time_label,swipe_right_ratio,swipe_right_label,likes_received,mutual_matches,profile_pics_count,bio_length,message_sent_count,emoji_usage_rate,last_active_hour,swipe_time_of_day,match_outcome
0,Prefer Not to Say,Gay,Urban,High,Bachelor’s,"Fitness, Politics, Traveling",52,Moderate,0.60,Optimistic,173,23,4,44,75,0.36,13,Early Morning,Mutual Match
1,Male,Bisexual,Suburban,Upper-Middle,No Formal Education,"Languages, Fashion, Parenting",279,Extreme User,0.56,Optimistic,107,7,3,301,35,0.42,0,Morning,Chat Ignored
2,Non-binary,Pansexual,Suburban,Low,Master’s,"Movies, Reading, DIY",49,Moderate,0.41,Optimistic,91,27,2,309,33,0.41,1,After Midnight,Date Happened
3,Genderfluid,Gay,Metro,Very Low,Postdoc,"Coding, Podcasts, History",185,Extreme User,0.32,Balanced,147,6,5,35,5,0.07,21,Morning,No Action
4,Male,Bisexual,Urban,Middle,Bachelor’s,"Clubbing, Podcasts, Cars",83,High,0.32,Balanced,94,11,1,343,34,0.11,22,After Midnight,One-sided Like
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,Transgender,Gay,Metro,Very High,Postdoc,"Gaming, Writing, Painting",130,Addicted,0.69,Optimistic,99,8,5,235,9,0.19,15,Afternoon,Ghosted
49996,Female,Lesbian,Small Town,Low,Diploma,"Traveling, Fitness, Stand-up Comedy",277,Extreme User,0.43,Optimistic,173,1,1,278,69,0.23,2,Evening,Ghosted
49997,Male,Bisexual,Remote Area,High,High School,"Gaming, Motorcycling, Art",73,High,0.50,Optimistic,123,8,1,128,94,0.36,5,After Midnight,Blocked
49998,Transgender,Queer,Urban,Low,MBA,"Skating, Astrology, Hiking",100,High,0.34,Balanced,149,19,3,206,53,0.36,16,Evening,One-sided Like
49999,Prefer Not to Say,Pansexual,Metro,Lower-Middle,Bachelor’s,"Crafting, Spirituality, Coding",119,High,0.56,Optimistic,114,17,0,395,68,0.50,16,Early Morning,No Action

In [22]:
type(df)

pandas.core.frame.DataFrame

In [23]:
# Data Exploration ---> Attribute & Functions for the dataframe

## Attributes

#### 1. shape ---> it provides the info about the (row,column) information about the dataset
#### syntax --<> df.shape

#### 2. dtypes --> It provides the idea about the datatype of all columns, so all columns with their name and their associated data type will be shown by using dtypes
#### syntax---> df.types

#### 3. index --> for a Dataframe with labelled index we can get the idea about the label just by using index attribute

#### 4. columns ---> it provides the idea about all of the column names of the give dataframe

#### 5. values --> it provides the idea about the values present row by row inside the dataframe. it always returns a 2D numpy array representing the values of column row by row

#### 6. ndim ---> it provides the idea about the dimension of the dataframe

#### 7. size ---> Total number of elements present inside the dataframe, that means all rows * all columns (Column 1 ---> 50 rows, column 2---> 50 rows .....)

In [24]:
df

,gender,sexual_orientation,location_type,income_bracket,education_level,interest_tags,app_usage_time_min,app_usage_time_label,swipe_right_ratio,swipe_right_label,likes_received,mutual_matches,profile_pics_count,bio_length,message_sent_count,emoji_usage_rate,last_active_hour,swipe_time_of_day,match_outcome
0,Prefer Not to Say,Gay,Urban,High,Bachelor’s,"Fitness, Politics, Traveling",52,Moderate,0.60,Optimistic,173,23,4,44,75,0.36,13,Early Morning,Mutual Match
1,Male,Bisexual,Suburban,Upper-Middle,No Formal Education,"Languages, Fashion, Parenting",279,Extreme User,0.56,Optimistic,107,7,3,301,35,0.42,0,Morning,Chat Ignored
2,Non-binary,Pansexual,Suburban,Low,Master’s,"Movies, Reading, DIY",49,Moderate,0.41,Optimistic,91,27,2,309,33,0.41,1,After Midnight,Date Happened
3,Genderfluid,Gay,Metro,Very Low,Postdoc,"Coding, Podcasts, History",185,Extreme User,0.32,Balanced,147,6,5,35,5,0.07,21,Morning,No Action
4,Male,Bisexual,Urban,Middle,Bachelor’s,"Clubbing, Podcasts, Cars",83,High,0.32,Balanced,94,11,1,343,34,0.11,22,After Midnight,One-sided Like
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,Transgender,Gay,Metro,Very High,Postdoc,"Gaming, Writing, Painting",130,Addicted,0.69,Optimistic,99,8,5,235,9,0.19,15,Afternoon,Ghosted
49996,Female,Lesbian,Small Town,Low,Diploma,"Traveling, Fitness, Stand-up Comedy",277,Extreme User,0.43,Optimistic,173,1,1,278,69,0.23,2,Evening,Ghosted
49997,Male,Bisexual,Remote Area,High,High School,"Gaming, Motorcycling, Art",73,High,0.50,Optimistic,123,8,1,128,94,0.36,5,After Midnight,Blocked
49998,Transgender,Queer,Urban,Low,MBA,"Skating, Astrology, Hiking",100,High,0.34,Balanced,149,19,3,206,53,0.36,16,Evening,One-sided Like
49999,Prefer Not to Say,Pansexual,Metro,Lower-Middle,Bachelor’s,"Crafting, Spirituality, Coding",119,High,0.56,Optimistic,114,17,0,395,68,0.50,16,Early Morning,No Action

In [25]:
df.shape

(50000, 19)

In [26]:
df.dtypes

gender                   object
sexual_orientation       object
location_type            object
income_bracket           object
education_level          object
interest_tags            object
app_usage_time_min        int64
app_usage_time_label     object
swipe_right_ratio       float64
swipe_right_label        object
likes_received            int64
mutual_matches            int64
profile_pics_count        int64
bio_length                int64
message_sent_count        int64
emoji_usage_rate        float64
last_active_hour          int64
swipe_time_of_day        object
match_outcome            object
dtype: object

In [27]:
df.index

RangeIndex(start=0, stop=50000, step=1)

In [28]:
df.columns

Index(['gender', 'sexual_orientation', 'location_type', 'income_bracket',
       'education_level', 'interest_tags', 'app_usage_time_min',
       'app_usage_time_label', 'swipe_right_ratio', 'swipe_right_label',
       'likes_received', 'mutual_matches', 'profile_pics_count', 'bio_length',
       'message_sent_count', 'emoji_usage_rate', 'last_active_hour',
       'swipe_time_of_day', 'match_outcome'],
      dtype='object')

In [29]:
df.values

array([['Prefer Not to Say', 'Gay', 'Urban', ..., 13, 'Early Morning',
        'Mutual Match'],
       ['Male', 'Bisexual', 'Suburban', ..., 0, 'Morning',
        'Chat Ignored'],
       ['Non-binary', 'Pansexual', 'Suburban', ..., 1, 'After Midnight',
        'Date Happened'],
       ...,
       ['Male', 'Bisexual', 'Remote Area', ..., 5, 'After Midnight',
        'Blocked'],
       ['Transgender', 'Queer', 'Urban', ..., 16, 'Evening',
        'One-sided Like'],
       ['Prefer Not to Say', 'Pansexual', 'Metro', ..., 16,
        'Early Morning', 'No Action']], shape=(50000, 19), dtype=object)

In [30]:
df.values[0]

array(['Prefer Not to Say', 'Gay', 'Urban', 'High', 'Bachelor’s',
       'Fitness, Politics, Traveling', 52, 'Moderate', 0.6, 'Optimistic',
       173, 23, 4, 44, 75, 0.36, 13, 'Early Morning', 'Mutual Match'],
      dtype=object)

In [31]:
df.size

950000

# Functions

#### 1. head()--> to get to have the idea about the data that your dataset is storing as the top 5 rows, that means that starting from the top we can get the top 5 rows and along with that if i want that instead of top 5 rows i want to see a fixed no. of rows from the rows, that number i can pass inside the head() as a paramenter

#### 2. tail() ---> provide the insight about the dataframe from the botton so tail() can show us the bottom 5 rows and again based on the value you will be passing as the parameter, those many values you can get using the tail fn()

#### 3. sample() ---> provides the insight about the dataframe as the random values present inside the dataset and again based on how many values i want i can put the parameter as per that

#### 4. info() ---> info() provides the idea --->
#### 1. about the datatype of all columns
#### 2. Number of Missing values of all columns
#### 3. Dataframe storage in Memory

#### 5. describe() ---> it provides an idea as the mathematical summary of the data --> minimum, maximum, count, mean, std, 25%, 50%, 75%

In [32]:
df.head()

,gender,sexual_orientation,location_type,income_bracket,education_level,interest_tags,app_usage_time_min,app_usage_time_label,swipe_right_ratio,swipe_right_label,likes_received,mutual_matches,profile_pics_count,bio_length,message_sent_count,emoji_usage_rate,last_active_hour,swipe_time_of_day,match_outcome
0,Prefer Not to Say,Gay,Urban,High,Bachelor’s,"Fitness, Politics, Traveling",52,Moderate,0.60,Optimistic,173,23,4,44,75,0.36,13,Early Morning,Mutual Match
1,Male,Bisexual,Suburban,Upper-Middle,No Formal Education,"Languages, Fashion, Parenting",279,Extreme User,0.56,Optimistic,107,7,3,301,35,0.42,0,Morning,Chat Ignored
2,Non-binary,Pansexual,Suburban,Low,Master’s,"Movies, Reading, DIY",49,Moderate,0.41,Optimistic,91,27,2,309,33,0.41,1,After Midnight,Date Happened
3,Genderfluid,Gay,Metro,Very Low,Postdoc,"Coding, Podcasts, History",185,Extreme User,0.32,Balanced,147,6,5,35,5,0.07,21,Morning,No Action
4,Male,Bisexual,Urban,Middle,Bachelor’s,"Clubbing, Podcasts, Cars",83,High,0.32,Balanced,94,11,1,343,34,0.11,22,After Midnight,One-sided Like

In [33]:
df.tail()

,gender,sexual_orientation,location_type,income_bracket,education_level,interest_tags,app_usage_time_min,app_usage_time_label,swipe_right_ratio,swipe_right_label,likes_received,mutual_matches,profile_pics_count,bio_length,message_sent_count,emoji_usage_rate,last_active_hour,swipe_time_of_day,match_outcome
49995,Transgender,Gay,Metro,Very High,Postdoc,"Gaming, Writing, Painting",130,Addicted,0.69,Optimistic,99,8,5,235,9,0.19,15,Afternoon,Ghosted
49996,Female,Lesbian,Small Town,Low,Diploma,"Traveling, Fitness, Stand-up Comedy",277,Extreme User,0.43,Optimistic,173,1,1,278,69,0.23,2,Evening,Ghosted
49997,Male,Bisexual,Remote Area,High,High School,"Gaming, Motorcycling, Art",73,High,0.50,Optimistic,123,8,1,128,94,0.36,5,After Midnight,Blocked
49998,Transgender,Queer,Urban,Low,MBA,"Skating, Astrology, Hiking",100,High,0.34,Balanced,149,19,3,206,53,0.36,16,Evening,One-sided Like
49999,Prefer Not to Say,Pansexual,Metro,Lower-Middle,Bachelor’s,"Crafting, Spirituality, Coding",119,High,0.56,Optimistic,114,17,0,395,68,0.50,16,Early Morning,No Action

In [34]:
df.sample()

,gender,sexual_orientation,location_type,income_bracket,education_level,interest_tags,app_usage_time_min,app_usage_time_label,swipe_right_ratio,swipe_right_label,likes_received,mutual_matches,profile_pics_count,bio_length,message_sent_count,emoji_usage_rate,last_active_hour,swipe_time_of_day,match_outcome
44407,Transgender,Demisexual,Suburban,Low,Associate’s,"Art, Cooking, Social Activism",114,High,0.45,Optimistic,47,6,5,55,97,0.38,0,Evening,Ghosted

In [35]:
df.sample(5)

,gender,sexual_orientation,location_type,income_bracket,education_level,interest_tags,app_usage_time_min,app_usage_time_label,swipe_right_ratio,swipe_right_label,likes_received,mutual_matches,profile_pics_count,bio_length,message_sent_count,emoji_usage_rate,last_active_hour,swipe_time_of_day,match_outcome
47016,Male,Asexual,Small Town,Upper-Middle,No Formal Education,"Yoga, MMA, Startups",173,Addicted,0.41,Optimistic,98,3,4,364,26,0.16,7,After Midnight,Mutual Match
9716,Male,Gay,Rural,High,Master’s,"Pets, K-pop, Traveling",151,Addicted,0.23,Balanced,75,2,5,159,22,0.50,10,After Midnight,Instant Match
19610,Transgender,Bisexual,Metro,Lower-Middle,PhD,"Painting, Pets, K-pop",163,Addicted,0.36,Balanced,4,0,5,166,84,0.62,20,Morning,No Action
21003,Non-binary,Pansexual,Remote Area,Low,High School,"Tech, Foodie, Traveling",61,High,0.59,Optimistic,30,16,1,242,58,0.21,22,Early Morning,Blocked
12377,Non-binary,Gay,Remote Area,Middle,No Formal Education,"Gaming, Spirituality, K-pop",172,Addicted,0.77,Swipe Maniac,149,25,2,463,96,0.12,5,Evening,One-sided Like

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   gender                50000 non-null  object
 1   sexual_orientation    50000 non-null  object
 2   location_type         50000 non-null  object
 3   income_bracket        50000 non-null  object
 4   education_level       50000 non-null  object
 5   interest_tags         50000 non-null  object
 6   app_usage_time_min    50000 non-null  int64
 7   app_usage_time_label  50000 non-null  object
 8   swipe_right_ratio     50000 non-null  float64
 9   swipe_right_label     50000 non-null  object
 10  likes_received        50000 non-null  int64
 11  mutual_matches        50000 non-null  int64
 12  profile_pics_count    50000 non-null  int64
 13  bio_length            50000 non-null  int64
 14  message_sent_count    50000 non-null  int64
 15  emoji_usage_rate      50000 non-null  float64
 16  last_active_hour      50000 non-null  int64
 17  swipe_time_of_day     50000 non-null  object
 18  match_outcome         50000 non-null  object
dtypes: float64(2), int64(7), object(10)
memory usage: 7.2+ MB

In [37]:
df.describe()

,app_usage_time_min,swipe_right_ratio,likes_received,mutual_matches,profile_pics_count,bio_length,message_sent_count,emoji_usage_rate,last_active_hour
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.00000,50000.000000,50000.000000
mean,149.912400,0.500655,99.526040,13.870280,2.98772,250.174400,50.07194,0.286205,11.521800
std,86.990521,0.197468,57.996799,9.105615,1.99678,144.800996,29.16800,0.160042,6.920474
min,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000
25%,74.000000,0.370000,49.000000,6.000000,1.00000,125.000000,25.00000,0.160000,5.000000
50%,150.000000,0.500000,100.000000,13.000000,3.00000,250.000000,50.00000,0.270000,12.000000
75%,225.000000,0.640000,150.000000,22.000000,5.00000,376.000000,75.00000,0.390000,18.000000
max,300.000000,1.000000,200.000000,30.000000,6.00000,500.000000,100.00000,0.940000,23.000000