In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\daksh\anaconda10\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\daksh\anaconda10\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\daksh\anaconda10\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\daksh\anaconda10\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\daksh\anaconda10\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\daksh\anaconda10\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
import pandas as pd

## Pandas Series is a cloumn of data in a Table like in Excel or Google Sheets with labels called as indexes attached to each value.

In [3]:
pd.Series(data=[40,50,60], index=['Bread','Milk','Butter'], name='Price of Grocery Items')

Bread     40
Milk      50
Butter    60
Name: Price of Grocery Items, dtype: int64

### Series is a 1D Array that can hold any type of data like integers, float, strings(object), boolean,mixed data type.

### Data type ---> Integers ---> Data in a Series(Column)--->Quantity of items in the Stock
### Data type ---> Float ---> Data in Series (Column) ---> Price or Product Ratings
### Data type ---> Strings ---> Column ---> Product Name
### Data type ---> Boolean ---> Column ---> Is item in stocl?
### Data type ---> Dates / Times ---> Column ---> Expiry Dates or sales Dates
### Mixed Types ---> Milk,40,True

## Creating a series in multiple ways
### 1. List
### 2. Numpy Array
### 3. Dictionary
### 4. Custom Index
### 5. Scalar Value

In [4]:
# Series from list

country=['India','China','USA','Pakistan']

pd.Series(country)

0       India
1       China
2         USA
3    Pakistan
dtype: object

In [5]:
batsman_runs=[48,64,72,98,114,183]
pd.Series(batsman_runs,dtype='int32')

0     48
1     64
2     72
3     98
4    114
5    183
dtype: int32

In [6]:
subject_names=['Math','Physics','Chemistry','Biology','English']
subject_marks=[34,54,23,45,64]

pd.Series(data=subject_marks,index=subject_names,name='Marks Scored' )

Math         34
Physics      54
Chemistry    23
Biology      45
English      64
Name: Marks Scored, dtype: int64

In [7]:
## creating a series using numpy arrays
values=np.arange(10,21)
pd.Series(values)

0     10
1     11
2     12
3     13
4     14
5     15
6     16
7     17
8     18
9     19
10    20
dtype: int64

In [8]:
## Dictionaries to series

## Dictionaries is another data structure that stores the data in a key value pair and just because it 
# stores the data in akey value pair we dont have to explicitly mention the index

data_items={'Maths':78,'English':92,'Physics':76}
pd.Series(data_items)

Maths      78
English    92
Physics    76
dtype: int64

In [9]:
# custom index to series
values=[1,2,3,4,5,6]
pd.Series(data=values, index=['a','b','c','d','e','f'])

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [10]:
# scalar value inside an series
pd.Series(4,
index=['a','b','c','d','e','f'])

a    4
b    4
c    4
d    4
e    4
f    4
dtype: int64

In [3]:
# read_csv()--> This function reads the content from the csv file in pandas so that we can perform 
# the operations on the data or we can perform effective analysis

Data=pd.read_csv("youtube_2025_dataset_202504061614.csv")

In [4]:
Data

,Channel Name,Youtuber Name,Total Videos,Best Video,Avg Video Length (min),Total Subscribers,Members Count,AI Generated Content (%),Neural Interface Compatible,Metaverse Integration Level,Quantum Computing Topics,Holographic Content Rating,Engagement Score,Content Value Index
0,Smith-Ross Labs,Eric Patel,68,VR Challenge: Review 2023,24.8,8264152,303319,9,True,Full,5,3D,130655.44,6.2
1,Sandoval PLC Hub,Cynthia Harrington,128,Nanotech Simulation: Analysis 2024,22.9,8768222,384629,62,False,NaN,4,3D,138624.73,21.4
2,"Jones, Moore and Ho Network",Amanda Walker,282,Metaverse Interface: Analysis 2024,24.0,6163386,361743,31,True,Advanced,6,1D,97442.53,13.5
3,Mitchell-Hooper Labs,Jessica Nelson MD,302,VR Protocol: Review 2023,24.6,4712268,58483,5,False,NaN,15,1D,74500.50,12.0
4,Wilson LLC Studios,Matthew Sherman,129,Nanotech Simulation: Review 2024,24.6,9592017,333873,63,True,NaN,12,3D,151648.85,27.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Flores-Daniel Studios,Jasmine Smith,106,AI Challenge: Experience 2023,22.0,2665835,267828,19,True,Full,1,3D,42146.59,6.4
4996,Spencer and Sons Studios,John Rasmussen,130,VR Challenge: Analysis 2023,26.3,136992,20019,67,True,Full,14,4D,2165.83,29.9
4997,Obrien-Roberts Studios,Lisa Burke,179,AI Challenge: Experience 2023,25.2,2314561,407346,99,True,Advanced,5,1D,36592.98,33.2
4998,King Ltd Hub,Steve Diaz,182,VR Synthesis: Showcase 2023,24.5,6954832,308313,1,True,Basic,9,4D,109955.22,6.6
4999,Henry Ltd Studios,Austin Tate,92,AI Simulation: Showcase 2025,25.2,6785166,23263,52,True,Full,8,3D,107272.81,21.2

In [5]:
df = pd.read_csv('youtube_2025_dataset_202504061614.csv')

In [ ]:
# DataFrame--->. Combination of Multiple Series(Column)
# squeeze---> squeeze parameter makes sure that the data is in series format
# index_col---> df = pd.read_csv('youtube_2025_dataset_202504061614.csv',index_col='Youtuber Name').squeeze('columns)

In [18]:
## Attribute in Series 
# 1. .values --> representing only the values of the given series
# 2. .index-->  returns only the index values from the given column
# 3. .dtype--> Dtype provides the idea about the data type of the values that you are storing 
# 4. .size---> this attribute provides the idea about the total number of rows inside the dataset
# 5. .shape --> this attribute provides the idea about the row column information
# 6. .ndim--> provides the idea about the dimension of the given dataset
# 7. .name --> this attribute provides the idea about the name of the series
# 8. .is_unique ---> this attribute helps us to know whether the values inside the series are unique or not

## Series Methods
#### 1. head()---> Provides the Top Preview of Data as the Top 5 Rows of the dataframe or series. It  is quite helpful with providing the preview of the dataset and if we want to preview top 10 rows then we can pass 10 as a argument or for top 7 rows we can pass 7 as an argument.

#### 2. tail()--> provides the bottom preview of Data as the Bottom 5 Rows.

#### for eg ---> dataset ---> salary column ---> top 5 rows ---> salary ---> 7 LPA ---> top 10 ---> top 15.... tail() ---> bottom 5 rows ---> salary ---> 4 LPA,9 LPA

#### 3. sample() ---> sample() provides any custom row from the dataset for us to preview it

#### 4. value_counts()---> it provides the idea about the count of the values (categorical values), if i am having a column where the categorical value count i want to calculate then i can go with value_counts()

#### 5. sort_values() --> this method sorts the value in an ascending manner. it can be useful for us fot the numerical columns. you can sort the value in descending manner as well

#### 6. sort_index() ---> this method sorts the index of the dataset.

In [15]:
df.values

array([['Smith-Ross Labs', 'Eric Patel', 68, ..., '3D', 130655.44,
        6.199999999999999],
       ['Sandoval PLC Hub', 'Cynthia Harrington', 128, ..., '3D',
        138624.73, 21.4],
       ['Jones, Moore and Ho Network', 'Amanda Walker', 282, ..., '1D',
        97442.53, 13.499999999999998],
       ...,
       ['Obrien-Roberts Studios', 'Lisa Burke', 179, ..., '1D', 36592.98,
        33.2],
       ['King Ltd Hub', 'Steve Diaz', 182, ..., '4D', 109955.22, 6.6],
       ['Henry Ltd Studios', 'Austin Tate', 92, ..., '3D', 107272.81,
        21.2]], shape=(5000, 14), dtype=object)

In [16]:
df.size

70000

In [19]:
youtube =pd.read_csv('youtube_2025_dataset_202504061614.csv')

In [20]:
avg = youtube['Avg Video Length (min)']

In [21]:
avg

0       24.8
1       22.9
2       24.0
3       24.6
4       24.6
        ...
4995    22.0
4996    26.3
4997    25.2
4998    24.5
4999    25.2
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [22]:
type(avg)

pandas.core.series.Series

In [23]:
avg.value_counts()

Avg Video Length (min)
24.1    276
23.8    264
23.9    256
24.2    253
24.0    251
       ...
20.6      1
28.0      1
21.0      1
20.7      1
21.1      1
Name: count, Length: 78, dtype: int64

In [24]:
avg.sort_values()

500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [ ]:
# parameter--> ascending = false (sorting---> descending)

In [25]:
avg.sort_values(ascending=False)

361     28.9
1467    28.4
364     28.3
925     28.1
2748    28.0
        ...
3704    20.7
171     20.6
1713    19.9
451     19.3
500     19.1
Name: Avg Video Length (min), Length: 5000, dtype: float64

## Method chaining --> we will ues multiple methods together to get the required required value in a way the first method's output will be second method input then 2nd method output will be 3rd method input

In [26]:
avg.sort_values(ascending=False).head(1)

361    28.9
Name: Avg Video Length (min), dtype: float64

In [27]:
avg.sort_values(ascending=False).head(1).values[0]

np.float64(28.9)

In [28]:
avg

0       24.8
1       22.9
2       24.0
3       24.6
4       24.6
        ...
4995    22.0
4996    26.3
4997    25.2
4998    24.5
4999    25.2
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [29]:
## In order to make a change in our data permanent --> inplace

avg

0       24.8
1       22.9
2       24.0
3       24.6
4       24.6
        ...
4995    22.0
4996    26.3
4997    25.2
4998    24.5
4999    25.2
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [30]:
avg.sort_values()

500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [32]:
average_data=avg.copy()

In [33]:
average_data

0       24.8
1       22.9
2       24.0
3       24.6
4       24.6
        ...
4995    22.0
4996    26.3
4997    25.2
4998    24.5
4999    25.2
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [34]:
average_data.sort_values(inplace=True)

In [35]:
average_data

500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [9]:
print(youtube.head())

                  Channel Name       Youtuber Name  Total Videos  \
0              Smith-Ross Labs          Eric Patel            68
1             Sandoval PLC Hub  Cynthia Harrington           128
2  Jones, Moore and Ho Network       Amanda Walker           282
3         Mitchell-Hooper Labs   Jessica Nelson MD           302
4           Wilson LLC Studios     Matthew Sherman           129

                           Best Video  Avg Video Length (min)  \
0           VR Challenge: Review 2023                    24.8
1  Nanotech Simulation: Analysis 2024                    22.9
2  Metaverse Interface: Analysis 2024                    24.0
3            VR Protocol: Review 2023                    24.6
4    Nanotech Simulation: Review 2024                    24.6

   Total Subscribers  Members Count  AI Generated Content (%)  \
0            8264152         303319                         9
1            8768222         384629                        62
2            6163386         361743                        31
3            4712268          58483                         5
4            9592017         333873                        63

   Neural Interface Compatible Metaverse Integration Level  \
0                         True                        Full
1                        False                         NaN
2                         True                    Advanced
3                        False                         NaN
4                         True                         NaN

   Quantum Computing Topics Holographic Content Rating  Engagement Score  \
0                         5                         3D         130655.44
1                         4                         3D         138624.73
2                         6                         1D          97442.53
3                        15                         1D          74500.50
4                        12                         3D         151648.85

   Content Value Index
0                  6.2
1                 21.4
2                 13.5
3                 12.0
4                 27.3

In [15]:
subs=youtube['subscribers']

In [16]:
subs

0      16600000
1       4860000
2       4010000
3       2990000
4       2080000
         ...
125       11400
126       11200
127       11000
128       10900
129       10800
Name: subscribers, Length: 130, dtype: int64

## Mathematical Functions in Pandas
### 1. sum() --> sum of all values present in the series
### 2. product() ---> product of all values in the series
### 3. mean() ---> Mean provides us with the average value of the data column.
### for eg ---> Company data---> salary ---> average value for that column salary = 7,6,8,9,11 mean = (6+6+8+9+11)/5 ---> 8 LPA

### median()---> Median also provides the idea about the average of the data. for coming up with median, we need to SORT the values in Ascending manner and then the middle value after sorting the data --> median; data ---> salary---> 1 crore, 10 crore (Outlier) --> avg --> 7+8+6+9

### mode() --> mode provides us with the idea that which value is getting repeated maximum number of times.

### std()--> if i need to get the idea that how the values inside the series are distributed from the average or mean value then we can come up with the standard deviation
#### salary ---> 7,8,6,6.5,7.5 ---> low standard deviation
#### salary --> 7,15,4,20,28,17 ---> high standard deviation

### variance --> variance also provides the insight about the distribution of the data from the mean value and variance is the square of the standard deviation.

#### standard_deviation = |mean - v_1| + |mean - v_2| ..../total count of values
#### variance = std**2

### min() ---> minimum value in the series
### max() --> maximum value in the series
### describe() ---> describe function provides the idea about the summary of the important mathematical calculaations for the data.

#### min---> minimum value
#### max--> maximum value
#### mean--> average value
#### std --> standard deviation
#### 25%---> 255 of the values out of my all values are less than this specific value
#### 50% ---> 50% of the values out of all my values are less than this value
#### 75% ---> 75% of the values out of all my values are less than this specific value

#### count--> total number of rouws in the column

##### JEE mains ---> 25% ---> my score in jee maiins was greater than 25% of the total applicants who applied in jee

In [18]:
subs.sum()

np.int64(66604700)

In [19]:
subs.product()

np.int64(0)

In [20]:
subs.sort_values()

129       10800
128       10900
127       11000
126       11200
125       11400
         ...
4       2080000
3       2990000
2       4010000
1       4860000
0      16600000
Name: subscribers, Length: 130, dtype: int64

In [21]:
subs.mean()

np.float64(512343.8461538461)

In [22]:
subs.median()

120000.0

In [23]:
subs.mode()

0    120000
Name: subscribers, dtype: int64

In [26]:
avg=youtube['total_views']

In [27]:
avg

0      9092244390
1       257598451
2       870967915
3       178609297
4        82120292
          ...
125        302138
126       6878757
127        130381
128        587499
129        839331
Name: total_views, Length: 130, dtype: int64

In [28]:
avg.std()

806890880.2699572

In [29]:
avg.var()

6.510728926628264e+17

In [30]:
avg.min()

26785

In [32]:
avg.max()

9092244390

In [33]:
avg.describe()

count    1.300000e+02
mean     1.237155e+08
std      8.068909e+08
min      2.678500e+04
25%      2.681172e+06
50%      1.059262e+07
75%      3.823083e+07
max      9.092244e+09
Name: total_views, dtype: float64

## Indexing in Series (To have the access over the  certain value or values)

### 1.Positive Indexing (Just like list) --> start from 0 to forward direction
### 2. No negative indexing
### 3. Slicing --> In the sries we can get the certain values over a given specific range and we can do it using [initial_val:final_val + 1]
### 3. Fancy Indexing ---> If i want the specific values from the series then we can go with fancy indexing
### 5. Indexing with Labels ---> A series which is consisting of labels as the index or custom index, then for this data we can retrieve the info using that custom index or label

In [34]:
avg

0      9092244390
1       257598451
2       870967915
3       178609297
4        82120292
          ...
125        302138
126       6878757
127        130381
128        587499
129        839331
Name: total_views, Length: 130, dtype: int64

In [35]:
avg[0]

np.int64(9092244390)

In [36]:
avg[5]

np.int64(628661984)

In [37]:
avg(-1)

TypeError: 'Series' object is not callable

In [38]:
avg[7:18]

7      293634526
8      105351847
9     1247156348
10     110240344
11     250689795
12      56374730
13     104029236
14      44883407
15     309863327
16      35150876
17     117271612
Name: total_views, dtype: int64

In [39]:
## If i eant the values skipped as a certain value
avg[2:21:2]

2     870967915
4      82120292
6     131666208
8     105351847
10    110240344
12     56374730
14     44883407
16     35150876
18    197934117
20    143994316
Name: total_views, dtype: int64

In [40]:
## Reverse values in a series
avg[::-1]

129        839331
128        587499
127        130381
126       6878757
125        302138
          ...
4        82120292
3       178609297
2       870967915
1       257598451
0      9092244390
Name: total_views, Length: 130, dtype: int64

In [42]:
avg[[2,3,4,5,6,3]]

2    870967915
3    178609297
4     82120292
5    628661984
6    131666208
3    178609297
Name: total_views, dtype: int64

In [44]:
df

,channel_id,channel_name,description,subscribers,total_views,total_videos,created_date,country,uploads_playlist,scraped_at
0,UCXuqSBlHAE6Xw-yeJA0Tunw,Linus Tech Tips,"Linus Tech Tips is a passionate team of ""profe...",16600000,9092244390,6989,2008-11-25T00:46:52Z,CA,UUXuqSBlHAE6Xw-yeJA0Tunw,2025-11-20T13:37:53.306286
1,UCWv7vMbMWH4-V0ZXdmDpPBA,Programming with Mosh,"Hi! I'm Mosh 👋, a software engineer with over ...",4860000,257598451,243,2014-10-07T00:40:53Z,US,UUWv7vMbMWH4-V0ZXdmDpPBA,2025-11-20T13:37:53.306286
2,UChIZGfcnjHI0DG4nweWEduw,TechSource,Join the Discord Server:\nhttps://discord.gg/T...,4010000,870967915,1897,2010-01-24T22:34:11Z,US,UUhIZGfcnjHI0DG4nweWEduw,2025-11-20T13:37:53.306286
3,UC4SVo0Ue36XCfOyb5Lh1viQ,Bro Code,Coding bootcamps HATE HIM! 🗿\n,2990000,178609297,1000,2019-10-10T14:40:46.568078Z,US,UU4SVo0Ue36XCfOyb5Lh1viQ,2025-11-20T13:37:53.306286
4,UCVeW9qkBjo3zosnqUbG7CFw,John Hammond,Free Cybersecurity Education and Ethical Hacking.,2080000,82120292,1740,2011-02-06T03:59:46Z,US,UUVeW9qkBjo3zosnqUbG7CFw,2025-11-20T13:37:53.306286
...,...,...,...,...,...,...,...,...,...,...
125,UCBKM3HATRILZyG9jGNJKGXQ,Software Engineering Daily,The world through the lens of software. \n\n🎙️...,11400,302138,1138,2017-05-19T21:45:38Z,US,UUBKM3HATRILZyG9jGNJKGXQ,2025-11-20T13:37:53.306286
126,UCvckuc-3Sos1aUtSqCV_0xw,Georgia Web Development,"Georgia Web Development is a Moultrie, Georgia...",11200,6878757,212,2014-03-17T20:28:26Z,US,UUvckuc-3Sos1aUtSqCV_0xw,2025-11-20T13:37:53.306286
127,UC4lM4hz_v5ixNjK54UwPEVw,Machine Learning and AI Academy,"Welcome to Machine Learning and AI Academy, yo...",11000,130381,60,2019-12-26T13:37:41.612225Z,GB,UU4lM4hz_v5ixNjK54UwPEVw,2025-11-20T13:37:53.306286
128,UCTnOFmMwZIi7jJYS_nAfeyQ,The Helpful Hacker,Welcome to The Helpful Hacker! I’m a passionat...,10900,587499,64,2024-06-17T17:08:58.598812Z,US,UUTnOFmMwZIi7jJYS_nAfeyQ,2025-11-20T13:37:53.306286
129,UCHd1qamEkVSlTWkEqIqJbEQ,Visual Computer Science,Welcome to Visual Computer Science! This chann...,10800,839331,35,2020-06-07T09:55:36.218375Z,US,UUHd1qamEkVSlTWkEqIqJbEQ,2025-11-20T13:37:53.306286

In [45]:
youtube

,channel_id,channel_name,description,subscribers,total_views,total_videos,created_date,country,uploads_playlist,scraped_at
0,UCXuqSBlHAE6Xw-yeJA0Tunw,Linus Tech Tips,"Linus Tech Tips is a passionate team of ""profe...",16600000,9092244390,6989,2008-11-25T00:46:52Z,CA,UUXuqSBlHAE6Xw-yeJA0Tunw,2025-11-20T13:37:53.306286
1,UCWv7vMbMWH4-V0ZXdmDpPBA,Programming with Mosh,"Hi! I'm Mosh 👋, a software engineer with over ...",4860000,257598451,243,2014-10-07T00:40:53Z,US,UUWv7vMbMWH4-V0ZXdmDpPBA,2025-11-20T13:37:53.306286
2,UChIZGfcnjHI0DG4nweWEduw,TechSource,Join the Discord Server:\nhttps://discord.gg/T...,4010000,870967915,1897,2010-01-24T22:34:11Z,US,UUhIZGfcnjHI0DG4nweWEduw,2025-11-20T13:37:53.306286
3,UC4SVo0Ue36XCfOyb5Lh1viQ,Bro Code,Coding bootcamps HATE HIM! 🗿\n,2990000,178609297,1000,2019-10-10T14:40:46.568078Z,US,UU4SVo0Ue36XCfOyb5Lh1viQ,2025-11-20T13:37:53.306286
4,UCVeW9qkBjo3zosnqUbG7CFw,John Hammond,Free Cybersecurity Education and Ethical Hacking.,2080000,82120292,1740,2011-02-06T03:59:46Z,US,UUVeW9qkBjo3zosnqUbG7CFw,2025-11-20T13:37:53.306286
...,...,...,...,...,...,...,...,...,...,...
125,UCBKM3HATRILZyG9jGNJKGXQ,Software Engineering Daily,The world through the lens of software. \n\n🎙️...,11400,302138,1138,2017-05-19T21:45:38Z,US,UUBKM3HATRILZyG9jGNJKGXQ,2025-11-20T13:37:53.306286
126,UCvckuc-3Sos1aUtSqCV_0xw,Georgia Web Development,"Georgia Web Development is a Moultrie, Georgia...",11200,6878757,212,2014-03-17T20:28:26Z,US,UUvckuc-3Sos1aUtSqCV_0xw,2025-11-20T13:37:53.306286
127,UC4lM4hz_v5ixNjK54UwPEVw,Machine Learning and AI Academy,"Welcome to Machine Learning and AI Academy, yo...",11000,130381,60,2019-12-26T13:37:41.612225Z,GB,UU4lM4hz_v5ixNjK54UwPEVw,2025-11-20T13:37:53.306286
128,UCTnOFmMwZIi7jJYS_nAfeyQ,The Helpful Hacker,Welcome to The Helpful Hacker! I’m a passionat...,10900,587499,64,2024-06-17T17:08:58.598812Z,US,UUTnOFmMwZIi7jJYS_nAfeyQ,2025-11-20T13:37:53.306286
129,UCHd1qamEkVSlTWkEqIqJbEQ,Visual Computer Science,Welcome to Visual Computer Science! This chann...,10800,839331,35,2020-06-07T09:55:36.218375Z,US,UUHd1qamEkVSlTWkEqIqJbEQ,2025-11-20T13:37:53.306286

## Editing Series(Bring the changes into the values stores inside the series)

#### 1. Using indexing ---> df[0]=65 ---> changing the original value at index 0 to 65

KeyError: 'Linus Tech Tips'